import {Poppins } from "next/font/google";
import "./globals.css";

const font  = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font",
  subsets: ["latin"],
});



export const metadata = {
  title: "Estudantes App",
  icons: {
    icon: "/icons/favicon.ico",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${font.variable}`}>
        {children}
      </body>
    </html>
  );
}
